// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aclluclfiiibahomeetq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjbGx1Y2xmaWlpYmFob21lZXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MzMxODIsImV4cCI6MjA1NjAwOTE4Mn0.unP_5tGi1neKH5jQ2IsZifPFbXrLOR50hDNXyRm4vmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);