// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvrywmshqmiudpvzgxgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52cnl3bXNocW1pdWRwdnpneGdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMDkzMjgsImV4cCI6MjA3Mjc4NTMyOH0.myhPvbCvwkQPuCuyo3TsfDNRZhGuKSYRrHIzlX4efK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});